config/routes.rb
Tweets::Application.routes.draw do

  root :to => 'favorite_tweets#last_tweets'
  match 'favorite_tweets/old_tweets/:the_oldest_id' => 'favorite_tweets#old_tweets'
  match 'favorite_tweets/new_tweets/:the_newest_id' => 'favorite_tweets#new_tweets'
  resources :favorite_tweets
  

end

app/models/favorite_tweet.rb
class FavoriteTweet < ActiveRecord::Base
  attr_accessible :tweet_id, :tweet_text, :tweet_time
  default_scope :order => "tweet_id DESC"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/favorite_tweets_controller.rb
class FavoriteTweetsController < ActionController::Base
	helper_method :favorite_tweets

  	def last_tweets
  		@posts = Twitter.user_timeline("ciklum")
  		render :layout => 'application'
	end

	def old_tweets
  		@posts = Twitter.user_timeline("ciklum", {:max_id => params[:the_oldest_id].to_i - 1, :count => 20})
  		render :layout => false
	end

	def new_tweets
  		@posts = Twitter.user_timeline("ciklum", {:since_id => params[:the_newest_id].to_i})
  		render :layout => false
	end

	def index
		@posts = FavoriteTweet.all
		render :layout => 'application'
	end

	def create
		tweet = Twitter.status(params[:tweet_id])
		FavoriteTweet.create :tweet_id => params[:tweet_id], :tweet_text => tweet.text, :tweet_time => tweet.created_at
		render :nothing => true
	end

	def destroy
		tweet = FavoriteTweet.find_by_tweet_id params[:id]
		tweet.destroy
		render :nothing => true
	end

	private

	def favorite_tweets
		@favorite_tweets ||= FavoriteTweet.all.map(&:tweet_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/favorite_tweets/_rows.html.erb
<% @posts.each do |post|%>
	<tr>
		<td>
			<%= post.created_at.strftime("%d.%m.%Y %R") %>
		</td>
		<td>
			<%= post.text %>
		</td>
		<td>
			<div class="favorite_add" id="<%= post[:id] %>">
				<% if favorite_tweets.include?(post[:id])%>
					<%= image_tag('star_icon.png', :alt => 'Tweet is already in favorite') %>
				<% else %>
					<%= link_to image_tag('star_icon_inactive.png', :alt => 'Add to favorite'), "#add" %>
				<% end %>
			</div>
		</td>
	</tr>
<% end %>

app/views/favorite_tweets/index.html.erb
<h1>
	Favorite @ciklum tweets
</h1>

<% content_for :page_links do %>
  <%= link_to "See last tweets", root_url %>
<% end %>

<table class="main" id="favorite_tweets_table">
	<tr>
		<th>Time</th>
		<th>Tweet</th>
		<th>Remove</th>
	</tr>
	<% @posts.each do |post|%>
		<tr class="favorite_remove" id="<%= post[:tweet_id] %>">
			<td>
				<%= post.tweet_time.strftime("%d.%m.%Y %R") %>
			</td>
			<td>
				<%= post.tweet_text %>
			</td>
			<td>
				<div><%= link_to "Remove", "#remove" %></div>
			</td>
		</tr>
	<% end %>
</table>

app/views/favorite_tweets/last_tweets.html.erb
<h1>
	Last @ciklum tweets
</h1>

<% content_for :page_links do %>
  <%= link_to "See favorite tweets", favorite_tweets_url %>
<% end %>

<div class="centered">
	<%= link_to "Refresh", "#new", :id => "new_tweets_link" %>
</div>

<table class="main" id="tweets_table">
	<tr>
		<th>Time</th>
		<th>Tweet</th>
		<th>Favorite</th>
	</tr>
	<%= render "rows" %>
</table>

<div class="centered">
	<%= link_to "Get older tweets", "#old", :id => "old_tweets_link" %>
</div>

app/views/favorite_tweets/new_tweets.html.erb
<%= render "rows" %>

app/views/favorite_tweets/old_tweets.html.erb
<%= render "rows" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield :page_links %>

<div class="main">
	<%= yield %>
</div>

</body>
</html>